# General
MISSING_FUNCTION = 10
INVALID_FUNCTION = 11
NO_UTF8 = 12
NO_JSON = 13

# Login
MISSING_USERNAME = 20
MISSING_PASSWORD = 21
INVALID_USERNAME_OR_PASSWORD = 22

# Authentication
MISSING_TOKEN = 30
INVALID_TOKEN = 31
